version: "3"
services:
  jenkins:
    image: jenkins
    container_name: myjenkins
    ports:
      - "8080:8080"
      # agent_port
      - "50000:50000"
    volumes:
      # sudo chown -R 1000:1000 ../app/log/jenkins
      - ../app/log/jenkins:/var/jenkins_home